language: java
jdk: oraclejdk8
script: mvn -Dmaven.test.skip=true package

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
        on_success: never
        on_failure: always
