language: java
jdk: oraclejdk8
script: "cd FrontEnd && mvn -Dmaven.test.skip=true package && cd ../Scanner && mvn -Dmaven.test.skip=true package && cd ../Converter && mvn -Dmaven.test.skip=true package && cd ../Presenter && mvn -Dmaven.test.skip=true package"
