language: java
jdk: oraclejdk8
script: mvn test

before_install:
  - pip install --user codecov
after_success:
  - codecov
  
notifications:
    email:
        on_success: never
        on_failure: always